### ISSUE TITLE
undefined method `hits' for nil:NilClass

### ISSUE THREAD

**Issue by bismoney** [biola/punching_bag#18]
<%= @post.hits %>

I can not understand why... :(

Rails 4.2.4
ruby 2.2.1p85

**Comment by adamcrown** [comment]
Base on the error message your `@posts` variable is `nil`. This likely isn't a problem with punching bag but if you'd like to give me a bit more context (the code in your controller is probably most important). I'll see if I can help you out.

**Comment by adamcrown** [comment]
It's been about a month with no response to this so I'm closing it. Let me know if you're still having problems and I'll reopen it.
