### ISSUE TITLE
Possible to do Post.sort_by_popularity('DESC', 1.day.ago)?

### ISSUE THREAD

**Issue by jensJJ** [biola/punching_bag#20]
Hello,

I would like to ask if it is possible to `sort_by_popularity` and consider the time.

sort_by_popularity uses all-time popularity. I would like to sort them via 1.day.ago popularity if that is possible with this gem. Thank you!

**Comment by adamcrown** [comment]
I think `#most_hit(1.day.ago, 1000000)` should do what you want.

`most_hit` does require a limit but obviously, if you set it high enough it won't kick in.
