### ISSUE TITLE
undefined method primary_key for Arel

### ISSUE THREAD

**Issue by hellojere** [biola/punching_bag#22]
I'm using `Rails 5.0.0.rc1` and when trying to get a list with `Post.most_hit(1.day.ago, 10)` I get the following error: 

```
undefined method `primary_key' for #<Arel::Table:0x007ffdcca4f610>
```

Any suggestions?

**Comment by adamcrown** [comment]
Thanks for letting me know. I haven't worked on Rails 5 compatibility with this gem yet. I'm a bit busy now but I'd be happy to merge a pull request. If not I'll get to this when I have time. Hopefully next week.

**Comment by hellojere** [comment]
Thanks. Will try to find some time as well, just not familiar with Arel really. 

Seems like the primary_key has been deprecated:
    
    primary_key (#{caller.first}) is deprecated and will be removed in Arel 4.0.0

**Comment by ryan-ol** [comment]
I'm on Rails 5.0.0.1 and have also encountered this error

**Comment by adamcrown** [comment]
Thanks for letting me know @ryan-ol. They must have made some changes to Arel in Rails 5. I'll try to come up with a solution when I have some free time. If you have any more info, please leave it here or feel free to submit a pull request. Thakns.

**Comment by adamcrown** [comment]
https://github.com/biola/punching_bag/pull/26 should have fixed this so I'm closing this issue.

@hellojere sorry for the very long delay it getting out a fix for this.
