### ISSUE TITLE
Rake punching_bag:combine gives error

### ISSUE THREAD

**Issue by Rubioli** [biola/punching_bag#25]
In readme/usage, it says I can run `rake punching_bag:combine` for combining hits.

when I run this `rake` I get error below:

    SELECT DISTINCT "punches"."punchable_type" FROM "punches"  ORDER BY punches.average_time DESC
          01 PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
          01 LINE 1: ...unches"."punchable_type" FROM "punches"  ORDER BY punches.av...
          01                                                              ^
          01 : SELECT DISTINCT "punches"."punchable_type" FROM "punches"  ORDER BY punches.average_time DESC
          01 rake aborted!
          01 ActiveRecord::StatementInvalid: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
          01 LINE 1: ...unches"."punchable_type" FROM "punches"  ORDER BY punches.av...
          01

This is a issue only on `production` ad since I use `pg` as my database.

What is wrong and how can I fix this issue?

**Comment by adamcrown** [comment]
This should be fixed by https://github.com/biola/punching_bag/pull/26 so I'm closing this.

@Rubioli sorry for the very long time in getting out a fix for this.
