### ISSUE TITLE
Pass hit count into `punch` method in acts_as_punchable modals

### ISSUE THREAD

**Issue by umhan35** [biola/punching_bag#9]
Currently I'm having to add a customize method having `Punch.create(punchable: self, hits: count)`. I would like to pass the count variable into https://github.com/biola/punching_bag/blob/master/lib/punching_bag/acts_as_punchable.rb#L26

**Comment by adamcrown** [comment]
My apologies that it's taken so very long for me to respond to this. I had been neglecting this project for a long time but I'm going to try to give it a little attention now.

This seems like a reasonable addition. I'll see if I can fit it in soon.

**Comment by adamcrown** [comment]
Just merged the PR to address this. I'll get a new gem version out soon.
